# Generated by Django 4.1 on 2022-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('initial_deviation', models.FloatField(default=69.44444444444446)),
                ('initial_rating', models.FloatField(default=8.333333333333334)),
                ('additional_variance', models.FloatField(default=17.361111111111114)),
                ('positive_lower_bound', models.FloatField(default=0.0001)),
            ],
            options={
                'db_table': 'ladder',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', related_query_name='match', to='ladder.ladder')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ranking', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to='ladder.match')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.team')),
            ],
            options={
                'db_table': 'team_player',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='ladder.TeamPlayer', to='ladder.player'),
        ),
        migrations.CreateModel(
            name='PlayerLadder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deviation', models.FloatField()),
                ('rating', models.FloatField()),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.player')),
            ],
            options={
                'db_table': 'player_ladder',
                'unique_together': {('ladder', 'player')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='ladders',
            field=models.ManyToManyField(related_name='players', related_query_name='player', through='ladder.PlayerLadder', to='ladder.ladder'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'number')},
        ),
    ]
